// Generated once from Chief-of-Staff/context/team.md (2026-10-03) to seed the org_people table.
// After first launch the database is the source of truth — edit the org in the Org view, not here.
import type { OrgSeedPerson } from './org'

export const ORG_SEED: OrgSeedPerson[] = [
  {
    "key": "clive-charlton",
    "name": "Clive Charlton",
    "role": "Group CTO",
    "tier": "CTO",
    "team": "Group Engineering",
    "manager": null,
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 0
  },
  {
    "key": "filipe-teixeira",
    "name": "Filipe Teixeira",
    "role": "Sr Eng Director, Group Fulfilment",
    "tier": "Director",
    "team": "Group Fulfilment",
    "manager": "clive-charlton",
    "stripe": "BU",
    "vacancy": false,
    "contractor": null,
    "order": 1
  },
  {
    "key": "mario-de-freitas",
    "name": "Mario De Freitas",
    "role": "Eng Director, Storefront",
    "tier": "Director",
    "team": "Storefront",
    "manager": "clive-charlton",
    "stripe": "BU",
    "vacancy": false,
    "contractor": null,
    "order": 2
  },
  {
    "key": "jonathan-muir",
    "name": "Jonathan Muir",
    "role": "CTO, Mr D",
    "tier": "Director",
    "team": "Mr D",
    "manager": "clive-charlton",
    "stripe": "BU",
    "vacancy": false,
    "contractor": null,
    "order": 3
  },
  {
    "key": "pieter-rautenbach",
    "name": "Pieter Rautenbach",
    "role": "Eng Director, Merchant",
    "tier": "Director",
    "team": "Merchant",
    "manager": "clive-charlton",
    "stripe": "BU",
    "vacancy": false,
    "contractor": null,
    "order": 4
  },
  {
    "key": "charles-brittz",
    "name": "Charles Brittz",
    "role": "Eng Director, Group QA",
    "tier": "Director",
    "team": "Group QA",
    "manager": "clive-charlton",
    "stripe": "Horizontal Enabler",
    "vacancy": false,
    "contractor": null,
    "order": 5
  },
  {
    "key": "william-howard",
    "name": "William Howard",
    "role": "Eng Director, Platform",
    "tier": "Director",
    "team": "Platform",
    "manager": "clive-charlton",
    "stripe": "Horizontal Enabler",
    "vacancy": false,
    "contractor": null,
    "order": 6
  },
  {
    "key": "danie-nagel",
    "name": "Danie Nagel",
    "role": "Eng Director, Data",
    "tier": "Director",
    "team": "Data",
    "manager": "clive-charlton",
    "stripe": "Horizontal Enabler",
    "vacancy": false,
    "contractor": null,
    "order": 7
  },
  {
    "key": "axel-tidemann",
    "name": "Axel Tidemann",
    "role": "Group Head of AI",
    "tier": "Director",
    "team": "AI",
    "manager": "clive-charlton",
    "stripe": "Specialist",
    "vacancy": false,
    "contractor": null,
    "order": 8
  },
  {
    "key": "ryan-hendriks",
    "name": "Ryan Hendriks",
    "role": "Head of Strategy & Innovation",
    "tier": "Director",
    "team": "Strategy & Innovation",
    "manager": "clive-charlton",
    "stripe": "Specialist",
    "vacancy": false,
    "contractor": null,
    "order": 9
  },
  {
    "key": "ulvi-guliyev",
    "name": "Ulvi Guliyev",
    "role": "Principal Engineer, AI Engineering Practice",
    "tier": "Principal",
    "team": "AI Engineering Practice",
    "manager": "clive-charlton",
    "stripe": "Specialist",
    "vacancy": false,
    "contractor": "Living Tensor",
    "order": 10
  },
  {
    "key": "renier-hugo",
    "name": "Renier Hugo",
    "role": "Group CIO, Group IT",
    "tier": "Director",
    "team": "Group IT",
    "manager": "clive-charlton",
    "stripe": "Group CIO scope",
    "vacancy": false,
    "contractor": null,
    "order": 11
  },
  {
    "key": "wilhelm-ellmann",
    "name": "Wilhelm Ellmann",
    "role": "Eng Manager 2",
    "tier": "EM2",
    "team": "Self Service Backend",
    "manager": "mario-de-freitas",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 12
  },
  {
    "key": "jean-louis-kroon",
    "name": "Jean-Louis Kroon",
    "role": "Eng Manager 2",
    "tier": "EM2",
    "team": "Storefront App (Android + iOS)",
    "manager": "mario-de-freitas",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 13
  },
  {
    "key": "righardt-swanepoel",
    "name": "Righardt Swanepoel",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Discovery Backend",
    "manager": "mario-de-freitas",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 14
  },
  {
    "key": "nicole-bell",
    "name": "Nicole Bell",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Storefront Web",
    "manager": "mario-de-freitas",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 15
  },
  {
    "key": "ross-allardice",
    "name": "Ross Allardice",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Payments Backend",
    "manager": "mario-de-freitas",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 16
  },
  {
    "key": "damon-hook",
    "name": "Damon Hook",
    "role": "Principal Eng 1",
    "tier": "Principal",
    "team": "Divisional",
    "manager": "mario-de-freitas",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 17
  },
  {
    "key": "kyle-govender",
    "name": "Kyle Govender",
    "role": "Eng Manager 2",
    "tier": "EM2",
    "team": "Catalogue",
    "manager": "pieter-rautenbach",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 18
  },
  {
    "key": "eugene-genis",
    "name": "Eugene Genis",
    "role": "Eng Manager 2",
    "tier": "EM2",
    "team": "Bsys",
    "manager": "pieter-rautenbach",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 19
  },
  {
    "key": "deon-bredenhann",
    "name": "Deon Bredenhann",
    "role": "Eng Manager 2",
    "tier": "EM2",
    "team": "RBS",
    "manager": "pieter-rautenbach",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 20
  },
  {
    "key": "megan-blazic",
    "name": "Megan Blazic",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "RBS / Retail",
    "manager": "pieter-rautenbach",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 21
  },
  {
    "key": "cobus-carstens",
    "name": "Cobus Carstens",
    "role": "Principal Eng 1",
    "tier": "Principal",
    "team": "Catalogue",
    "manager": "pieter-rautenbach",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 22
  },
  {
    "key": "henrico-bekker",
    "name": "Henrico Bekker",
    "role": "Eng Manager 2",
    "tier": "EM2",
    "team": "Discovery ML / FML/MML",
    "manager": "axel-tidemann",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 23
  },
  {
    "key": "byron-sorgdrager",
    "name": "Byron Sorgdrager",
    "role": "Eng Manager 2",
    "tier": "EM2",
    "team": "DBA & DataOps",
    "manager": "william-howard",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 24
  },
  {
    "key": "storm-joubert",
    "name": "Storm Joubert",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "DevOps",
    "manager": "william-howard",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 25
  },
  {
    "key": "stii-pretorius",
    "name": "Stii Pretorius",
    "role": "Principal Engineer",
    "tier": "Principal",
    "team": "SRE",
    "manager": "william-howard",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 26
  },
  {
    "key": "vacancy-william-howard-1",
    "name": "Vacancy",
    "role": "Principal Engineer",
    "tier": "Principal",
    "team": "SRE",
    "manager": "william-howard",
    "stripe": null,
    "vacancy": true,
    "contractor": null,
    "order": 27
  },
  {
    "key": "marc-wells",
    "name": "Marc Wells",
    "role": "Eng Manager 2",
    "tier": "EM2",
    "team": "Data Platform",
    "manager": "danie-nagel",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 28
  },
  {
    "key": "muhammed-tootla",
    "name": "Muhammed Tootla",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Data Eng",
    "manager": "danie-nagel",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 29
  },
  {
    "key": "benjamin-smith",
    "name": "Benjamin Smith",
    "role": "BI Manager 2",
    "tier": "EM2",
    "team": "BI",
    "manager": "danie-nagel",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 30
  },
  {
    "key": "magen-vadivelu",
    "name": "Magen Vadivelu",
    "role": "BI Manager 1",
    "tier": "EM1",
    "team": "BI (Takealot)",
    "manager": "danie-nagel",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 31
  },
  {
    "key": "kudakwashe-nyamutsambira",
    "name": "Kudakwashe Nyamutsambira",
    "role": "BI Manager 1",
    "tier": "EM1",
    "team": "Analytics",
    "manager": "danie-nagel",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 32
  },
  {
    "key": "bianca-pretorius",
    "name": "Bianca Pretorius",
    "role": "Analytics Manager",
    "tier": "EM1",
    "team": "Data Monetize",
    "manager": "danie-nagel",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 33
  },
  {
    "key": "deepa-naicker",
    "name": "Deepa Naicker",
    "role": "QA Manager 2",
    "tier": "EM2",
    "team": "Storefront QA",
    "manager": "charles-brittz",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 34
  },
  {
    "key": "theo-van-staden",
    "name": "Theo van Staden",
    "role": "QA Manager 2",
    "tier": "EM2",
    "team": "Merchant QA",
    "manager": "charles-brittz",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 35
  },
  {
    "key": "nozipho-mbonambi",
    "name": "Nozipho Mbonambi",
    "role": "QA Manager 1",
    "tier": "EM1",
    "team": "Logistics QA",
    "manager": "charles-brittz",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 36
  },
  {
    "key": "carla-kruger",
    "name": "Carla Kruger",
    "role": "QA Manager 1",
    "tier": "EM1",
    "team": "Logistics QA",
    "manager": "charles-brittz",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 37
  },
  {
    "key": "jared-petersen",
    "name": "Jared Petersen",
    "role": "QA Manager 1",
    "tier": "EM1",
    "team": "Stock Mgmt & WMS",
    "manager": "charles-brittz",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 38
  },
  {
    "key": "phindile-shezi",
    "name": "Phindile Shezi",
    "role": "QA Manager 1",
    "tier": "EM1",
    "team": "Storefront Apps QA",
    "manager": "charles-brittz",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 39
  },
  {
    "key": "ronald-higgins",
    "name": "Ronald Higgins",
    "role": "Eng Manager 2",
    "tier": "EM2",
    "team": "Infrasec",
    "manager": "renier-hugo",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 40
  },
  {
    "key": "paul-malherbe",
    "name": "Paul Malherbe",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "IT Support",
    "manager": "renier-hugo",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 41
  },
  {
    "key": "sven-willmann",
    "name": "Sven Willmann",
    "role": "Director Platform",
    "tier": "Director",
    "team": "Platform",
    "manager": "jonathan-muir",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 42
  },
  {
    "key": "craig-bowring",
    "name": "Craig Bowring",
    "role": "Eng Manager 2",
    "tier": "EM2",
    "team": "Site Reliability",
    "manager": "jonathan-muir",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 43
  },
  {
    "key": "petr-chavik",
    "name": "Petr Chavik",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "iOS / Consumer Apps",
    "manager": "jonathan-muir",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 44
  },
  {
    "key": "andre-gomes",
    "name": "Andre Gomes",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Consumer Apps",
    "manager": "jonathan-muir",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 45
  },
  {
    "key": "gareth-west",
    "name": "Gareth West",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Web",
    "manager": "jonathan-muir",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 46
  },
  {
    "key": "doug-falconer",
    "name": "Doug Falconer",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Platform Eng",
    "manager": "jonathan-muir",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 47
  },
  {
    "key": "stephen-hunter",
    "name": "Stephen Hunter",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Site Reliability",
    "manager": "jonathan-muir",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 48
  },
  {
    "key": "sarita-vd-walt",
    "name": "Sarita vd Walt",
    "role": "Agile Manager",
    "tier": "EM1",
    "team": "Consumer Apps",
    "manager": "jonathan-muir",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 49
  },
  {
    "key": "kurt-campher",
    "name": "Kurt Campher",
    "role": "Agile Dlv Lead",
    "tier": "Other",
    "team": "",
    "manager": "jonathan-muir",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 50
  },
  {
    "key": "ferdie-nell",
    "name": "Ferdie Nell",
    "role": "QA Manager 1",
    "tier": "EM1",
    "team": "QA",
    "manager": "jonathan-muir",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 51
  },
  {
    "key": "pieter-lourens",
    "name": "Pieter Lourens",
    "role": "Eng Director",
    "tier": "Director",
    "team": "Logistics",
    "manager": "filipe-teixeira",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 52
  },
  {
    "key": "campbell-morrison",
    "name": "Campbell Morrison",
    "role": "Eng Director",
    "tier": "Director",
    "team": "Supply Chain",
    "manager": "filipe-teixeira",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 53
  },
  {
    "key": "vacancy-filipe-teixeira-1",
    "name": "Vacancy",
    "role": "Eng Director",
    "tier": "Director",
    "team": "",
    "manager": "filipe-teixeira",
    "stripe": null,
    "vacancy": true,
    "contractor": null,
    "order": 54
  },
  {
    "key": "kevin-tomsett",
    "name": "Kevin Tomsett",
    "role": "Eng Manager 2",
    "tier": "EM2",
    "team": "Network",
    "manager": "pieter-lourens",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 55
  },
  {
    "key": "placky-motema",
    "name": "Placky Motema",
    "role": "Eng Manager 2",
    "tier": "EM2",
    "team": "On Demand Planning",
    "manager": "pieter-lourens",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 56
  },
  {
    "key": "gerard-mopp",
    "name": "Gerard Mopp",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "On Demand Execution",
    "manager": "pieter-lourens",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 57
  },
  {
    "key": "jateen-singh",
    "name": "Jateen Singh",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Planning",
    "manager": "pieter-lourens",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 58
  },
  {
    "key": "tania-rall",
    "name": "Tania Rall",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Tracking",
    "manager": "pieter-lourens",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 59
  },
  {
    "key": "vacancy-pieter-lourens-1",
    "name": "Vacancy",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "TalNOW",
    "manager": "pieter-lourens",
    "stripe": null,
    "vacancy": true,
    "contractor": null,
    "order": 60
  },
  {
    "key": "peter-wrench",
    "name": "Peter Wrench",
    "role": "Eng Manager 2",
    "tier": "EM2",
    "team": "Inbound",
    "manager": "campbell-morrison",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 61
  },
  {
    "key": "daniel-smith",
    "name": "Daniel Smith",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Outbound",
    "manager": "campbell-morrison",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 62
  },
  {
    "key": "duran-cole",
    "name": "Duran Cole",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Stock Management",
    "manager": "campbell-morrison",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 63
  },
  {
    "key": "william-francis",
    "name": "William Francis",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Fulfilment Web",
    "manager": "filipe-teixeira",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 64
  },
  {
    "key": "hassan-vawda",
    "name": "Hassan Vawda",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Fulfilment Mobile",
    "manager": "filipe-teixeira",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 65
  },
  {
    "key": "jarrod-clarke",
    "name": "Jarrod Clarke",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Fulfilment Orchestration",
    "manager": "filipe-teixeira",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 66
  },
  {
    "key": "shanette-ramnandh",
    "name": "Shanette Ramnandh",
    "role": "Eng Manager 2",
    "tier": "EM2",
    "team": "Operations / Support / Analysts",
    "manager": "filipe-teixeira",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 67
  },
  {
    "key": "vacancy-shanette-ramnandh-1",
    "name": "Vacancy",
    "role": "Eng Manager 1",
    "tier": "EM1",
    "team": "Engineering Operations",
    "manager": "shanette-ramnandh",
    "stripe": null,
    "vacancy": true,
    "contractor": null,
    "order": 68
  },
  {
    "key": "charles-van-wyk",
    "name": "Charles Van Wyk",
    "role": "Principal SE",
    "tier": "Principal",
    "team": "SRE",
    "manager": "filipe-teixeira",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 69
  },
  {
    "key": "jacques-botha",
    "name": "Jacques Botha",
    "role": "Principal SE",
    "tier": "Principal",
    "team": "SRE",
    "manager": "filipe-teixeira",
    "stripe": null,
    "vacancy": false,
    "contractor": null,
    "order": 70
  }
]
